config/routes.rb
Website::Application.routes.draw do

  root :to => "pages#home"

  match '/contact', :to => "pages#contact"
  match '/about',   :to => "pages#about"
  match '/experiments',   :to => "pages#experiments"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    default_title = "Rails App"
    if @title.nil?
      default_title
    else
      @title
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><a href="http://usu.edu/">USU</a></li>
      <li><a href="https://aggiemail.usu.edu/">Email</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= javascript_include_tag "jquery-1.7.2.min", "jquery-ui-1.8.20.custom.min" %>
  <%= javascript_include_tag :defaults %>
  
  <h3>Atul Thapliyal</h3>
  <%= image_tag("logo.png", :alt => "Rails App", :class => "round") %>
  <nav class = "round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'jquery-ui-1.8.20.custom', :media => 'screen' %>

app/views/layouts/_videos.html.erb
<video width="240" height="135" controls="controls">
  <source src=<%= video_path("video.ogg")%> type="video/ogg" />
</video>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>    
    <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class = "round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>    
  </body>
</html>

app/views/pages/_android.html.erb
<h5>My Android apps at Utah State University</h5>

<p>I took "Android development class" at Utah State and at that time it was just about completing my assignments in time. Today, I love writting Android code. When ever I get some free time, I try to complete my apps. Its becoming more like a hobby for me to write android code even though I have published only one app</p>


<h5><u>Projects</u></h5>

<ul>
  <li><b><u><a href="https://play.google.com/store/search?q=rockets+and+pumpkins/" target="_blank">RocketsAndPumpkins</a></u></b>
  	<ul>
  	  <li>Role - Software engineer </li>
  	  <li>Contribution - Design and development of the app</li>
  	  <li>Description - This is a simple interactive arcade game for visually impaired people as well as for people with no disabilities</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
  <br/>  

  <li><b>Where is my stuff</b>
  	<ul>
  	  <li>Role - Software engineer </li>
  	  <li>Contribution - Design and development of the application</li>
  	  <li>Description - This is a simple app where people can keep track of house hold items. Work in progress</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>

app/views/pages/_current.html.erb
<h5><u>Research Assistant/Software Engineer</u> at <a href="http://idias.usu.edu/" target="_blank">IDIAS</a>, Utah State University</h5>

<p> <b>Duration - </b> November, 2010 - Present </p> 

<p> 
Researching is always fun and when it is in the name of !! Gaming !! it means a real big screen and Xbox 360 :) 
Well, here is a brief background - Our group is developing an educational game (First person shooter) as a part of NSF grant "DRK12". It aims at teaching science to students of 8 grade. For example like how different states of matter has differnet molecular structure. Nearly 20 schools from Utah and 20 from NewYork are participating in this project. Its big.
</p>

<h5><u>Projects</u></h5>

<ul>
  <li><b><u><a href="http://idias.usu.edu/scape" target="_blank">S'cape (C#)</a></u></b>
  	<ul>
  	  <li>Role - Software Engineer </li>
  	  <li>Contribution - Design and development of the game</li>
  	  <li>Description - Development of an educational game using Unity3D engine and C# with automated assessment functionality and replay mode </li>
  	  <li>Team size - 4</li>
  	</ul>
  </li>
  <br/>

  <li><b><u><a href="http://geobobapp.usu.edu/" target="_blank">GeoBob(RoR)</a></u></b>
  	<ul>
  	  <li>Role - Software Engineer </li>
  	  <li>Contribution - Maintenance and adding new features </li>
  	  <li>Description - Used for developing GPS based mobile games. It is build using Rails 3.0.1, Ruby 1.8.7, JQuery, MySql</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
</ul>

app/views/pages/_education.html.erb
<h5><u>Schools</u></h5>

<ul>
  <li><b><u><a href="http://usu.edu/" target="_blank">Utah State University</a></u></b>
  	<ul>
  	  <li>Degree - M.S in Computer Science </li>
  	  <li>GPA - 3.71</li>
  	  <li>Expected  - September 2012</li>
  	</ul>
  </li>
  <br/>  

  <li><b><u><a href="http://abes.ac.in/" target="_blank">ABES Engineering College</a></u></b>
  	<ul>
  	  <li>Degree - B.Tech in Electronic and Communication </li>
  	  <li>Percentage - 68 %</li>
  	  <li>Completed on  - May, 2007</li>
  	</ul>
  </li>

app/views/pages/_hadoop.html.erb
<h5><u> Independent Study Project </u> at Utah State University</h5>

<p><b>Duration - </b> January, 2012 - Present</p>

<p> 
</p>

<h5><u>Project</u></h5>

<ul>
  <li><b>Profiling Pig queries in a Hadoop cluster</b>
  	<ul>
  	  <li>Role - Software Engineer</li>
  	  <li>Contribution - Set up of Hadoop cluster in the CS department lab using 5 Linux boxes, Setup of Pig, configuration of Yourit Java profiler to profile mapreduce jobs</li>
  	  <li>Description - This is my independent study project. </li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
</ul>
<ul>
	<li><b><a href="https://github.com/athap/LuceneProjects" target="_blank">LuceneBlogSearch</a></b>  
  	<ul>
  	  <li>Role - Software Engineer</li>
  	  <li>Contribution - Development of the project</li>
  	  <li>Description - I created this simple project in order to understand how lucene indexes documents. This projects creates some fake blog data and then indexes it. It uses Lucene 3.6</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
</ul>

app/views/pages/_internships.html.erb
<h5><u> Software Engineer Intern </u> at <a href="http://tatemae.com/" target="_blank">Tatemae</a></h5>

<p><b>Duration - </b> January, 2012 - Present</p>

<p> Tatemae, its a start up organization full of talented people :). Tatemae will be launching its new product soon and I am pretty sure its going to rock !! We write a lot of Ruby code here.

Well, Ruby reminded me of a quote.
<i>"Ruby is the language Buddha would have programmed in."
                                  -- Sean Russell, Author: REXML Ruby Library
</i>
Back to the topic
</p>

<h5><u>Projects</u></h5>

<ul>
  <li><b><a href="http://eportfolio.saylor.org/" target="_blank">ePortfolio(RoR)</a></b>
  	<ul>
  	  <li>Role - Software Engineer</li>
  	  <li>Contribution - Design and development of the application</li>
  	  <li>Description - This is an eportfolio system for open education students to maintain their courses and area of studies. It is build using Rails 3.2.1, Ruby 1.9.3, Backbone.js, JQuery, MySql  </li>
  	  <li>Team size - 10</li>
  	</ul>
  </li>
</ul>

app/views/pages/_java.html.erb
<h5>My Java/CSharp projects at Utah State University</h5>

<p>I write C# code each day as compared to Java but still I try to use Java whereever possible</p>


<h5><u>Projects</u></h5>

<ul>
  <li><b><a href="https://github.com/athap/JavaProjects/tree/master/WordChain" target="_blank">Word Ladder using Dijkstra's algorithm</a></b>   
    <ul>
      <li>Role - Software Engineer </li>
      <li>Contribution - Implementation of the algorithm</li>
      <li>Description - Implementation of Word ladder game(also known as a doublets, word-links, or Word golf) using Dijkstra's algorithm</li>
      <li>Team size - 1</li>
    </ul>
  </li>

  <li><b>Word Guessing Game in C#</b>
  	<ul>
  	  <li>Role - Software Engineer </li>
  	  <li>Contribution - Design and development of the application</li>
  	  <li>Description - This is a simple word guessing game based on a client and server</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
  <br/>

  <li><b>Travelling Sales Man in Java</b>
  	<ul>
  	  <li>Role - Software Engineer </li>
  	  <li>Contribution - Implementation of the algorithm</li>
  	  <li>Description - Implementation of travelling sales man problem using branch and bound algorithm</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
</ul>

app/views/pages/_past.html.erb
<h5><u>Project Engineer </u> at <a href="http://wipro.com/" target="_blank">Wipro Technologies</a></h5>

<p><b>Duration - </b> March, 2008 - March, 2010</p>

<p>
My past work experience includes working in Securities and Telecom domain for 
<a href="www.wipro.com" target="_blank">Wipro Technologies</a>, India 
</p>

<h5><u>Projects</u></h5>

<ul>
  <li><b><u>Toll Free Provisioning for Bell Canada</u></b>
  	<ul>
  	  <li>Role - Project Engineer </li>
      <li>Contribution - Design and development of migration and rollback utility </li>
  	  <li>Description -  Data was migrated from Tandem system to Oracle database using Java based ConceptWave Order Management tool</li>
  	  <li>Team size - 15</li>
  	</ul>
  </li>
  <br/>

  <li><b><u>Unitrax SRP for Citi Canada</u></b>
  	<ul>
  	  <li>Role - Project Engineer</li>
      <li>Contribution - Development of look up tables</li>
  	  <li>Description - Lookup tables were used to retrieve data which was displayed as a pop up using IBM RBD tool in EGL language</li>
  	  <li>Team size - 8</li>
  	</ul>
  </li>
</ul>

<p>Ya, I know, nothing interesting here. You probably need a red bull now. Well try another tab :)</p>

app/views/pages/_rubyonrails.html.erb
<h5>My RubyonRails projects at Utah State University</h5>

<p>Well, I am still learning Ruby on Rails and this website is a result of that. I mean its a simple website with a bunch of links. With the help of superb service by heroku, I was able to deploy my app for FREE. </p>


<h5><u>Projects</u></h5>

<ul>
  <li><b><u><a href="http://scape.herokuapp.com/" target="_blank">Scape Data Collection with d3.v2.js</a></u></b>
    <ul>
      <li>Role - Software Engineer </li>
      <li>Contribution - Design and development of the application</li>
      <li>Description - This is a data collection app for the 3D game Scape. In Scape, students takes quizzes at the end of each level. The results are sent to this app for analysis. Teachers can also download the data. Also, data visualization is provided with the help of <b>pie charts</b>. Specs - Rails 3.2.1, Ruby 1.9.3, d3.v2.js and Postgres</li>
      <li>Team size - 1</li>
    </ul>
  </li>
  <br/>

  <li><b><u><a href="http://atulthapliyal-mitra.heroku.com/" target="_blank">Mitra</a></u></b>
  	<ul>
  	  <li>Role - Software Engineer </li>
  	  <li>Contribution - Design and development of the application</li>
  	  <li>Description - This is a simple blogging application using Rails 3.0.5, Ruby 1.8.7 and Sqlite</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
  <br/>

  <br/>
  <li><b><u><a href="http://atulthapliyal.heroku.com/" target="_blank">My Website</a></u></b>
  	<ul>
  	  <li>Role - Software Engineer </li>
  	  <li>Contribution - Design and development of the application</li>
  	  <li>Description - This is my website using Rails 3.0.9, Ruby 1.8.7 and Sqlite</li>
  	  <li>Team size - 1</li>
  	</ul>
  </li>
</ul>

app/views/pages/about.html.erb
<div id="tweets">    
      <script>
        new TWTR.Widget({
          version: 2,
          type: 'profile',
          rpp: 6,
          interval: 30000,
          width: 200,
          height: 200,
          theme: {
            shell: {
              background: '#333333',
              color: '#ffffff'
            },
            tweets: {
              background: '#000000',
              color: '#ffffff',
              links: '#4aed05'
            }
          },
          features: {
            scrollbar: true,
            loop: false,
            live: false,
            behavior: 'all'
          }
        }).render().setUser('a_thap').start();
      </script>
    </div>

<p>
Hi !!
I am a masters student at <a href="www.usu.edu" target="_blank">Utah State University</a>, Computer Science. I like Logan city as it is close to the nature with beautiful summer. Camping and fishing are at the top of my to do list. I also work for <a href="http://idias.usu.edu/" target="_blank">IDIAS</a> with <a href="http://itls.usu.edu/htm/profile&brett-shelton" target="_blank">Dr. Brett Shelton</a>.
</p>

<p>
I am still learning how to be a better programmer and honestly, I try to learn by seeing how other good programmers code. I mostly write code in C# and Ruby
</p>

<p>
Surprisingly, my under grad was in Electronics & Communication, India, (2003 - 2007). Yes, I know a little about 8086 and those scary mosfets. After completing my under grad, I started working with Wipro Technologies (WT), India, as a Java developer. After working for 2.5 years I realised the importance of a masters degree and started explored my options for masters degree in Computer Science. 
<br>
This was my gateway to Utah State University.
<br>
<b>Thanks for reading.</b>
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p> You can find me at - atulDOTthapliyalATaggiemailDOTusuDOTedu</p>

<p>LinkedIn - <a href="http://www.linkedin.com/pub/atul-thapliyal/12/9a7/670">Atul Thapliyal</a></p>

app/views/pages/experiments.html.erb
<h3>OpenSim Virtual experiments</h3>
<object width="240" height="200">
  <param name="movie" value="http://www.youtube.com/v/YJNyGch9jkk&hl=en_US&fs=1&"></param>
  <param name="allowFullScreen" value="true"></param>
  <param name="allowscriptaccess" value="always"></param>
  <embed src="http://www.youtube.com/v/YJNyGch9jkk&hl=en_US&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always"
    allowfullscreen="true"  width="240"  height="200">
  </embed>
</object>
<object width="240" height="200">
  <param name="movie" value="http://www.youtube.com/v/91r3sP_1ciA&hl=en_US&fs=1&"></param>
  <param name="allowFullScreen" value="true"></param>
  <param name="allowscriptaccess" value="always"></param>
  <embed src="http://www.youtube.com/v/91r3sP_1ciA&hl=en_US&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always"
    allowfullscreen="true"  width="240"  height="200">
  </embed>
</object>
<object width="240" height="200">
  <param name="movie" value="http://www.youtube.com/v/46DBhAINH4c&hl=en_US&fs=1&"></param>
  <param name="allowFullScreen" value="true"></param>
  <param name="allowscriptaccess" value="always"></param>
  <embed src="http://www.youtube.com/v/46DBhAINH4c&hl=en_US&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always"
    allowfullscreen="true"  width="240"  height="200">
  </embed>
</object>

app/views/pages/home.html.erb
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Current</a></li>
    <li><a href="#tabs-2">Interships</a></li>
    <li><a href="#tabs-3">Past</a></li>
    <li><a href="#tabs-4">RoR</a></li>
    <li><a href="#tabs-5">Android</a></li>
    <li><a href="#tabs-6">Java/C#</a></li>    
    <li><a href="#tabs-7">Hadoop/Pig/Lucene</a></li>
    <li><a href="#tabs-8">Education</a></li>
  </ul>

  <div id="tabs-1">
    <%= render :partial => 'current' %>
  </div>

  <div id="tabs-2">
    <%= render :partial => 'internships' %>
  </div>

<div id="tabs-3">
    <%= render :partial => 'past' %>
  </div>

  <div id="tabs-4">
    <%= render :partial => 'rubyonrails' %>
  </div>
  
  <div id="tabs-5">
    <%= render :partial => 'android' %>
  </div>
    
  <div id="tabs-6">
    <%= render :partial => 'java' %>
  </div>

  <div id="tabs-7">
    <%= render :partial => 'hadoop' %>
  </div>

  <div id="tabs-8">
    <%= render :partial => 'education' %>
  </div>
</div>

<u><%#= link_to "Virtual Physics experiments for kids", experiments_path %></u>